title: ERT - Visualization tool

pages:

 - title: Plot Viewer
   content:
    - ResponseComparison:

 - title: Observation Analyzer
   content:
    - ObservationAnalyzer:

 - title: Parameter Comparison Viewer
   content:
    - ParameterComparison:
   experimental: True

 - title: Response Correlation Viewer
   content:
    - ResponseCorrelation:
   experimental: True
